[project]
name = "trafficdetector"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.123.4",
    "opencv-python-headless>=4.12.0.88",
    "supervision>=0.27.0",
    "ultralytics>=8.3.234",
]
